CREATE TABLE orders (
  order_number TEXT PRIMARY KEY,
  checkout_key TEXT NOT NULL UNIQUE,
  request_hash TEXT NOT NULL,
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  address_json TEXT NOT NULL CHECK (json_valid(address_json)),
  items_json TEXT NOT NULL CHECK (json_valid(items_json) AND json_array_length(items_json) > 0),
  currency TEXT NOT NULL DEFAULT 'BRL' CHECK (currency = 'BRL'),
  subtotal_cents INTEGER NOT NULL CHECK (subtotal_cents > 0),
  coupon TEXT NOT NULL,
  coupon_discount_cents INTEGER NOT NULL CHECK (coupon_discount_cents >= 0),
  pix_discount_cents INTEGER NOT NULL CHECK (pix_discount_cents >= 0),
  shipping_service_id INTEGER NOT NULL,
  shipping_name TEXT NOT NULL,
  shipping_company TEXT,
  shipping_cents INTEGER NOT NULL CHECK (shipping_cents >= 0),
  total_cents INTEGER NOT NULL CHECK (total_cents > 0 AND total_cents = subtotal_cents - coupon_discount_cents - pix_discount_cents + shipping_cents),
  payment_method TEXT NOT NULL CHECK (payment_method IN ('pix', 'other')),
  status TEXT NOT NULL DEFAULT 'aguardando pagamento' CHECK (status IN ('aguardando pagamento', 'pago', 'cancelado', 'estornado')),
  payment_setup_status TEXT NOT NULL DEFAULT 'not_started' CHECK (payment_setup_status IN ('not_started', 'creating', 'ready', 'review_required')),
  mercado_pago_payment_id TEXT UNIQUE,
  mercado_pago_preference_id TEXT UNIQUE,
  checkout_url TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  paid_at TEXT
);
CREATE INDEX orders_status_created ON orders(status, created_at);
